export const sampleEcsCartItem = {
  buyUrl:
    "https://console-intl.huaweicloud.com/ecm/?region=sa-brazil-1&locale=en-us&charging=0&flavor=x1.2u.4g&imageId=5e98a4a3-0d2e-4003-88ae-0a5619cce96a&sysdisk=GPSSD:40&datadisk=&iptype=&ipcharging=&bwsize=&vmcount=1&period=#/ecs/createVm",
  rewriteValue: {
    global_TITLE: {
      tag: "general.online.portal",
    },
    global_DESCRIPTION: "Elastic Cloud Server",
    global_REGIONINFO: {
      region: "sa-brazil-1",
      locationType: "commonAZ",
      chargeMode: "ONDEMAND",
    },
    template_RENDER: {
      calculator_ecs_radio: {
        arch: "dataInfo_32_",
        vmType: "dataInfo_1_",
        generation: "X1",
        cpu: "2dataInfo_36_",
        mem: "4BSSUNIT.pluralUnit.102",
      },
      calculator_evs_stepper: {
        calculator_evs_stepper_main: {
          type: "dataInfo_43_",
          UNSET_Stepper_0: {
            measureId: 17,
            measureValue: 40,
            measureNameBeforeTrans: "",
            measurePluralNameBeforeTrans: "",
            transRate: "",
            transTarget: "",
          },
        },
      },
    },
    global_ONDEMANDTIME: {
      UNSET_Stepper_0: {
        measureId: 4,
        measureValue: 744,
        measureNameBeforeTrans: "",
        measurePluralNameBeforeTrans: "",
        transRate: "",
        transTarget: "",
      },
    },
    global_QUANTITY: {
      UNSET_Stepper_0: {
        measureId: 41,
        measureValue: 1,
        measureNameBeforeTrans: "calc_29_",
        measurePluralNameBeforeTrans: "calc_30_",
        transRate: "",
        transTarget: "",
      },
    },
  },
  selectedProduct: {
    region: "sa-brazil-1",
    locationType: "commonAZ",
    chargeMode: "ONDEMAND",
    tag: "general.online.portal",
    serviceCode: "ecs",
    timeTag: 0,
    chargeModeName: "ONDEMAND",
    periodType: 4,
    periodNum: 1,
    subscriptionNum: 1,
    purchaseTime: {
      measureValue: 744,
      measureId: 4,
      measureNameBeforeTrans: "",
      measurePluralNameBeforeTrans: "",
    },
    purchaseNum: {
      measureValue: 1,
      measureId: 41,
      measureNameBeforeTrans: "calc_29_",
      measurePluralNameBeforeTrans: "calc_30_",
    },
    description: "Elastic Cloud Server",
    amount: 0,
    discountAmount: 0,
    originalAmount: 0,
    _customTitle: "Elastic Cloud Server",
    productAllInfos: [
      {
        resourceType: "hws.resource.type.vm",
        cloudServiceType: "hws.service.type.ec2",
        resourceSpecCode: "x1.2u.4g.linux",
        productId: "OFFI1012619014602915849",
        billingMode: "ONDEMAND",
        productNum: 1,
        selfProductNum: 1,
        usageValue: 744,
        usageMeasureId: 4,
        inquiryTag: "normal",
        addToList_product: "dataInfo_32_ | dataInfo_1_ | x1.2u.4g | 2dataInfo_36_ | 4BSSUNIT.pluralUnit.102",
        inquiryResult: {
          id: "sample-vm",
          productId: "OFFI1012619014602915849",
          amount: 0,
          discountAmount: 0,
          originalAmount: 0,
          perAmount: null,
          perDiscountAmount: null,
          perOriginalAmount: null,
          perPeriodType: null,
          measureId: 1,
          extendParams: null,
        },
      },
      {
        id: "5e98a4a3-0d2e-4003-88ae-0a5619cce96a",
        __os_type: "Linux",
        __platform: "AlmaLinux",
        __os_bit: "64",
        name: "AlmaLinux 9.4 64bit",
        type: ["x1"],
        productNum: 744,
        durationNum: 744,
        inquiryTag: "localImage",
        selfProductNum: 1,
        inquiryResult: {
          amount: 0,
          originalAmount: 0,
          discountAmount: 0,
          productId: "noId",
          id: "sample-image",
        },
      },
      {
        resourceType: "hws.resource.type.volume",
        cloudServiceType: "hws.service.type.ebs",
        resourceSpecCode: "GPSSD",
        productSpecSysDesc: "Disk Specifications:General Purpose SSD",
        resourceSpecType: "GPSSD",
        volumeType: "General Purpose SSD",
        billingItem: "detail_68_",
        type: "dataInfo_43_",
        info: "dataInfo_26_",
        specifications: "dataInfo_27_",
        tableUnit: "detail_26_",
        resourceMeasureName: "",
        resourceMeasurePluralName: "",
        addToList_title: "calc_11_",
        addToList_product: "dataInfo_43_ | 40BSSUNIT.pluralUnit.17",
        productId: "00301-247376-0--0",
        billingMode: "ONDEMAND",
        productNum: 1,
        selfProductNum: 1,
        inquiryTag: "normal",
        resourceSize: 40,
        usageValue: 744,
        usageMeasureId: 4,
        inquiryResult: {
          id: "sample-disk",
          productId: "00301-247376-0--0",
          amount: 0,
          discountAmount: 0,
          originalAmount: 0,
          perAmount: null,
          perDiscountAmount: null,
          perOriginalAmount: null,
          perPeriodType: null,
          measureId: 1,
          extendParams: null,
        },
      },
    ],
  },
} as const;
