import type { ConfigurableServiceBundleDefinition } from "@/lib/configurable-service-bundle-types";
import { and, call, coalesce, eq, ifElse, max, ref, template } from "@/lib/typed-declarative-runtime-ops";

export const configurableServiceBundle = {
  service: {
    version: 1,
    definitionId: "dcs",
    serviceCode: "DCS",
    serviceName: "Distributed Cache Service (for Redis)",
    icon: "https://res-static.hc-cdn.cn/cloudbu-site/public/product-banner-icon/Middleware/Memcached.png",
    implementation: "configurable",
    billingOptions: ["Pay-per-use"],
    defaults: {
      edition: "Basic",
      version: "7.0",
      instanceType: "Single-node",
      architecture: "x86 | DRAM",
      replicas: 2,
      specification: "4 GB",
      quantity: 1,
      elasticBandwidth: "Buy now",
      bandwidthMbit: 1,
      usageHours: 744,
    },
    fields: [
      { id: "edition", type: "select", label: "Edition", required: true, options: ["Basic"] },
      { id: "version", type: "select", label: "Version", required: true, optionsSource: "catalog.versions" },
      { id: "instanceType", type: "select", label: "Instance Type", required: true, optionsSource: "catalog.instanceTypes" },
      { id: "architecture", type: "select", label: "CPU / Memory", required: true, optionsSource: "catalog.architectures" },
      { id: "replicas", type: "select", label: "Replicas", required: true, optionsSource: "catalog.replicas", visibleWhen: { field: "showReplicas", equals: true } },
      { id: "specification", type: "select", label: "Specification", required: true, optionsSource: "catalog.specifications" },
      { id: "quantity", type: "number", label: "Quantity", required: true, min: 1, step: 1 },
      { id: "elasticBandwidth", type: "select", label: "Elastic Bandwidth", required: true, options: ["Buy now", "Buy later"] },
      { id: "bandwidthMbit", type: "number", label: "Bandwidth", required: true, unit: "Mbit/s", min: 1, step: 1, visibleWhen: { field: "elasticBandwidth", equals: "Buy now" } },
      { id: "usageHours", type: "number", label: "Required Duration", required: true, unit: "hours", min: 1, max: 87600, step: 24 },
    ],
    summary: {
      selectionTemplate: "{edition} | {version} | {instanceType} | {architecture} | {specification}",
      notes: [
        "This calculator currently models the Basic Redis pay-per-use flow.",
        "Bandwidth charges are included only when Elastic Bandwidth is set to Buy now.",
      ],
    },
  },
  pricing: {
    version: 1,
    definitionId: "dcs",
    serviceCode: "DCS",
    serviceName: "Distributed Cache Service (for Redis)",
    catalogAdapter: "dcs",
    rateSources: {
      instance: {
        catalogKey: "instanceTiers.prices",
        description: "Normalized Redis pay-per-use instance rates from the productInfo catalog.",
      },
      bandwidth: {
        catalogKey: "bandwidthRatePerMbitHour",
        description: "Normalized elastic bandwidth rate per Mbit/s per hour from the productInfo catalog.",
      },
    },
    metrics: [
      {
        id: "redisInstance",
        label: "Redis instances",
        rateSource: "instance",
        quantity: { source: "field", field: "quantity" },
      },
      {
        id: "elasticBandwidth",
        label: "Elastic bandwidth",
        rateSource: "bandwidth",
        quantity: { source: "field", field: "bandwidthMbit" },
        unit: "Mbit/s",
        enabledWhen: { field: "elasticBandwidth", equals: "Buy now" },
      },
    ],
  },
  catalogDefinition: {
    source: {
      displayName: "DCS",
      urlPath: "redis",
      tab: "calc",
    },
    parser: {
      kind: "recursive-grouped-records",
      currency: "USD",
      rootPath: "product",
      collectionKey: "instanceTiers",
      catalogStatic: {
        edition: "Basic",
      },
      recordFilters: [
        { kind: "text-includes", paths: ["resourceSpecCode", "productSpecSysDesc", "productId"], value: "redis" },
        { kind: "text-excludes", paths: ["resourceSpecCode", "productSpecSysDesc", "productId"], value: "bandwidth" },
        { kind: "field-not-equals", path: "product_type", value: "professional" },
        { kind: "field-not-equals", path: "resourceSpecType", value: "dcs_enterprise" },
        { kind: "text-excludes", paths: ["resourceSpecCode", "productSpecSysDesc", "productId"], value: "product_type:professional" },
      ],
      fields: [
        { key: "edition", extractor: { kind: "literal", value: "Basic" } },
        { key: "version", required: true, extractor: { kind: "enum-from-pattern", paths: ["versionKey", "version", "redisVersion", "engineVersion", "productSpecSysDesc", "resourceSpecCode", "productId"], values: ["7.0", "6.0", "5.0", "4.0"] } },
        {
          key: "instanceType",
          required: true,
          extractor: {
            kind: "keyword-map",
            directPath: "cache_mode",
            directMap: {
              single_node: "Single-node",
              cluster: "Redis Cluster",
              master_standby: "Master/Standby",
            },
            textPaths: ["instanceType", "type", "mode", "productSpecSysDesc", "resourceSpecCode", "productId"],
            mappings: [
              { keywords: ["single"], value: "Single-node" },
              { keywords: ["cluster"], value: "Redis Cluster" },
              { keywords: ["master", "standby"], value: "Master/Standby" },
              { keywords: ["ha"], value: "Master/Standby" },
            ],
          },
        },
        {
          key: "architecture",
          required: true,
          extractor: {
            kind: "keyword-map",
            directPath: "cpu",
            directMap: {
              aarch64: "ARM | DRAM",
              x86_64: "x86 | DRAM",
            },
            textPaths: ["architecture", "cpuArch", "cpuType", "productSpecSysDesc", "resourceSpecCode", "productId"],
            mappings: [
              { keywords: ["arm"], value: "ARM | DRAM" },
              { keywords: ["x86"], value: "x86 | DRAM" },
              { keywords: ["x64"], value: "x86 | DRAM" },
            ],
          },
        },
        { key: "memoryGiB", required: true, extractor: { kind: "memory-gib", paths: ["memory", "mem", "capacity", "size", "specification"] } },
        { key: "specification", extractor: { kind: "path-or-template", path: "specification", template: "{memoryGiB} GB" } },
        {
          key: "replicas",
          extractor: {
            kind: "replica-count",
            numberPaths: ["replicas", "replica", "replicaNum", "standbyNum", "slaveNum", "nodeNum", "repl_spec", "replica_Number"],
            textPaths: ["productSpecSysDesc", "resourceSpecCode", "productId"],
            fallbackByField: { field: "instanceType", equals: "Master/Standby", value: 2 },
          },
        },
        { key: "resourceSpecCode", extractor: { kind: "path-or-template", path: "resourceSpecCode", template: "{version}-{instanceType}-{architecture}-{memoryGiB}" } },
        { key: "prices", extractor: { kind: "rate-set", modes: ["ONDEMAND"] } },
        { key: "productIds.ONDEMAND", extractor: { kind: "plan-product-id", billingMode: "ONDEMAND" } },
      ],
      postRejectWhenAll: [
        [
          { field: "instanceType", notEquals: "Redis Cluster" },
          { field: "memoryGiB", gt: 64 },
        ],
        [
          { field: "instanceType", equals: "Redis Cluster" },
          { field: "memoryGiB", lt: 4 },
        ],
      ],
      dedupeBy: ["version", "instanceType", "architecture", "replicas", "specification"],
      minByPath: "prices.ONDEMAND",
      sort: [
        { path: "version", direction: "asc", order: ["7.0", "6.0", "5.0", "4.0"] },
        { path: "instanceType", direction: "asc", order: ["Single-node", "Master/Standby", "Redis Cluster"] },
        { path: "architecture", direction: "asc", order: ["x86 | DRAM", "ARM | DRAM"] },
        { path: "replicas", direction: "asc" },
        { path: "memoryGiB", direction: "asc" },
      ],
      auxiliaryOutputs: [
        {
          targetPath: "bandwidthRatePerMbitHour",
          extractor: {
            kind: "bandwidth-rate-per-unit",
            billingMode: "ONDEMAND",
            numberPaths: ["bandwidth", "bandwidthMbit", "measureValue", "value"],
            textPaths: ["productSpecSysDesc", "resourceSpecCode", "productId", "type"],
            textRegex: "(\\d+(?:\\.\\d+)?)\\s*mbit",
            defaultUnits: 1,
          },
          filters: [
            { kind: "text-includes", paths: ["type", "productSpecSysDesc", "resourceSpecCode", "productId"], value: "bandwidth" },
          ],
        },
      ],
    },
  },
  runtime: {
    quantityLabel: "Instance",
    showGlobalQuantityControl: false,
    usesSharedBillingHeader: true,
    catalog: { route: "dcs-pricing" },
    showSharedUsageHours: false,
    derived: [
      { key: "versionOptions", value: ifElse(ref("catalog"), call("listDcsVersions", ref("catalog")), []) },
      { key: "version", value: call("resolveOption", ref("values.version"), ref("derived.versionOptions"), ref("helpers.dcsDefaults.version")) },
      {
        key: "instanceTypeOptions",
        value: ifElse(ref("catalog"), call("listDcsInstanceTypes", ref("catalog"), ref("derived.version")), []),
      },
      { key: "instanceType", value: call("resolveOption", ref("values.instanceType"), ref("derived.instanceTypeOptions"), ref("helpers.dcsDefaults.instanceType")) },
      {
        key: "architectureOptions",
        value: ifElse(
          ref("catalog"),
          call("listDcsArchitectures", ref("catalog"), { version: ref("derived.version"), instanceType: ref("derived.instanceType") }),
          ["x86 | DRAM", "ARM | DRAM"],
        ),
      },
      { key: "architecture", value: call("resolveOption", ref("values.architecture"), ref("derived.architectureOptions"), ref("helpers.dcsDefaults.architecture")) },
      { key: "showReplicas", value: ifElse(eq(ref("derived.instanceType"), "Single-node"), false, true) },
      {
        key: "replicaOptions",
        value: ifElse(
          ref("catalog"),
          call("listDcsReplicas", ref("catalog"), { version: ref("derived.version"), instanceType: ref("derived.instanceType"), architecture: ref("derived.architecture") }),
          ifElse(
            eq(ref("derived.instanceType"), "Master/Standby"),
            [2, 3, 4, 5],
            ifElse(eq(ref("derived.instanceType"), "Redis Cluster"), [1, 2, 3, 4, 6], []),
          ),
        ),
      },
      {
        key: "replicas",
        value: ifElse(
          ref("derived.showReplicas"),
          call("resolveNumberOption", ref("values.replicas"), ref("derived.replicaOptions"), ref("helpers.dcsDefaults.replicas")),
          null,
        ),
      },
      {
        key: "specificationOptions",
        value: ifElse(
          ref("catalog"),
          call("listDcsSpecifications", ref("catalog"), {
            version: ref("derived.version"),
            instanceType: ref("derived.instanceType"),
            architecture: ref("derived.architecture"),
            replicas: ref("derived.replicas"),
          }),
          ifElse(
            eq(ref("derived.instanceType"), "Redis Cluster"),
            ["4 GB", "8 GB", "16 GB", "32 GB", "64 GB", "128 GB", "256 GB", "512 GB", "1024 GB"],
            ["0.125 GB", "0.25 GB", "0.5 GB", "1 GB", "2 GB", "4 GB", "8 GB", "16 GB", "32 GB", "64 GB"],
          ),
        ),
      },
      { key: "specification", value: call("resolveOption", ref("values.specification"), ref("derived.specificationOptions"), ref("helpers.dcsDefaults.specification")) },
      { key: "quantity", value: max(1, call("clampInteger", ref("values.quantity"), 1)) },
      { key: "elasticBandwidth", value: ifElse(eq(ref("values.elasticBandwidth"), "Buy later"), "Buy later", "Buy now") },
      { key: "bandwidthMbit", value: max(1, call("clampInteger", ref("values.bandwidthMbit"), 1)) },
      { key: "dcsUsageHoursValue", value: max(1, call("clampInteger", ref("values.usageHours"), 1, 87600)) },
      {
        key: "estimate",
        value: ifElse(
          ref("catalog"),
          call("estimateDcsConfiguration", ref("catalog"), {
            edition: "Basic",
            version: ref("derived.version"),
            instanceType: ref("derived.instanceType"),
            architecture: ref("derived.architecture"),
            replicas: ref("derived.replicas"),
            specification: ref("derived.specification"),
            quantity: ref("derived.quantity"),
            elasticBandwidth: ref("derived.elasticBandwidth"),
            bandwidthMbit: ref("derived.bandwidthMbit"),
            usageHours: ref("derived.dcsUsageHoursValue"),
          }),
          null,
        ),
      },
    ],
    syncValues: {
      edition: "Basic",
      version: ref("derived.version"),
      instanceType: ref("derived.instanceType"),
      architecture: ref("derived.architecture"),
      replicas: coalesce(ref("derived.replicas"), ref("helpers.dcsDefaults.replicas")),
      specification: ref("derived.specification"),
      quantity: ref("derived.quantity"),
      elasticBandwidth: ref("derived.elasticBandwidth"),
      bandwidthMbit: ref("derived.bandwidthMbit"),
      usageHours: ref("derived.dcsUsageHoursValue"),
    },
    visibilityContext: {
      showReplicas: ref("derived.showReplicas"),
      elasticBandwidth: ref("derived.elasticBandwidth"),
    },
    fieldRuntime: {
      edition: { disabled: true },
      version: { options: call("optionList", ref("derived.versionOptions")) },
      instanceType: { options: call("optionList", ref("derived.instanceTypeOptions")) },
      architecture: { options: call("optionList", ref("derived.architectureOptions")) },
      replicas: { options: call("optionList", ref("derived.replicaOptions")) },
      specification: { options: call("optionList", ref("derived.specificationOptions")) },
      quantity: { min: 1, normalize: ref("derived.quantity") },
      bandwidthMbit: { min: 1, normalize: ref("derived.bandwidthMbit") },
      usageHours: { min: 1, max: 87600, normalize: ref("derived.dcsUsageHoursValue") },
    },
    estimate: ref("derived.estimate"),
    addToListError: ifElse(ref("derived.estimate"), null, call("firstMeaningfulText", ref("pricingError"), "DCS pricing is unavailable for the current selection.")),
    selectionSummary: ifElse(
      ref("derived.estimate"),
      call(
        "joinSelectionParts",
        [
          "Selected specifications:",
          "Basic",
          ref("derived.version"),
          ref("derived.instanceType"),
          ref("derived.architecture"),
          ifElse(ref("derived.showReplicas"), template("{replicas} replicas", { replicas: ref("derived.replicas") }), null),
          ref("derived.specification"),
          template("{quantity} instance{suffix}", {
            quantity: ref("derived.quantity"),
            suffix: ifElse(eq(ref("derived.quantity"), 1), "", "s"),
          }),
          ifElse(eq(ref("derived.elasticBandwidth"), "Buy now"), template("Buy now {bandwidth} Mbit/s", { bandwidth: ref("derived.bandwidthMbit") }), "Buy later"),
          template("{hours}h", { hours: ref("derived.dcsUsageHoursValue") }),
          call("formatFlavorAmount", ref("derived.estimate.currency"), ref("derived.estimate.amount"), ref("derived.estimate.suffix")),
        ],
      ),
      "Selected specifications:",
    ),
    selectionNotes: ifElse(
      ref("derived.estimate"),
      call(
        "concatArrays",
        call("formatBreakdownNotes", ref("derived.estimate.currency"), ref("derived.estimate.suffix"), ref("derived.estimate.breakdown")),
        [template("Monthly average: {avg}.", { avg: call("formatFlavorAmount", ref("derived.estimate.currency"), ref("derived.estimate.monthlyAverageAmount"), "/mo") })],
        call("asArray", ref("derived.estimate.notes")),
      ),
      [],
    ),
    referenceNote: template(
      "Pricing sourced from Huawei Cloud DCS calculator API for {region}. Sources: {pricingUrl} and {productUrl}",
      {
        region: coalesce(ref("catalogRegionId"), call("getCatalogRegionId", ref("regionValue"))),
        pricingUrl: ref("helpers.dcsPricingReference.pricingUrl"),
        productUrl: ref("helpers.dcsPricingReference.productUrl"),
      },
    ),
    buildRequestBodies: ifElse(
      ref("derived.estimate"),
      {
        serviceCode: ref("selectedServiceCode"),
        serviceName: ref("selectedService"),
        productType: "dcs",
        title: template("{service} {version} {instanceType} {specification}", {
          service: ref("selectedService"),
          version: ref("derived.version"),
          instanceType: ref("derived.instanceType"),
          specification: ref("derived.specification"),
        }),
        quantity: 1,
        config: {
          region: ref("regionValue"),
          catalogRegionId: coalesce(ref("catalogRegionId"), call("getCatalogRegionId", ref("regionValue"))),
          billingMode: "Pay-per-use",
          edition: "Basic",
          version: ref("derived.version"),
          instanceType: ref("derived.instanceType"),
          architecture: ref("derived.architecture"),
          replicas: ifElse(ref("derived.showReplicas"), ref("derived.replicas"), null),
          specification: ref("derived.specification"),
          quantity: ref("derived.quantity"),
          elasticBandwidth: ref("derived.elasticBandwidth"),
          bandwidthMbit: ifElse(eq(ref("derived.elasticBandwidth"), "Buy now"), ref("derived.bandwidthMbit"), null),
          usageHours: ref("derived.dcsUsageHoursValue"),
          resourceSpecCode: ref("derived.estimate.tier.resourceSpecCode"),
          productId: ref("derived.estimate.tier.productIds.ONDEMAND"),
        },
        pricing: {
          total: call("formatFlavorAmount", ref("derived.estimate.currency"), ref("derived.estimate.amount"), ref("derived.estimate.suffix")),
          estimate: call("formatFlavorAmount", ref("derived.estimate.currency"), ref("derived.estimate.amount"), ref("derived.estimate.suffix")),
          monthlyAverage: call("formatFlavorAmount", ref("derived.estimate.currency"), ref("derived.estimate.monthlyAverageAmount"), "/mo"),
          breakdown: call("byLabelAmount", ref("derived.estimate.currency"), ref("derived.estimate.suffix"), ref("derived.estimate.breakdown")),
        },
      },
      null,
    ),
    hydrate: ifElse(
      and(eq(ref("product.productType"), "dcs"), call("isRecord", ref("product.config"))),
      {
        handled: true,
        values: {
          edition: "Basic",
          version: coalesce(ref("product.config.version"), ref("helpers.dcsDefaults.version")),
          instanceType: coalesce(ref("product.config.instanceType"), ref("helpers.dcsDefaults.instanceType")),
          architecture: coalesce(ref("product.config.architecture"), ref("helpers.dcsDefaults.architecture")),
          replicas: coalesce(ref("product.config.replicas"), ref("helpers.dcsDefaults.replicas")),
          specification: coalesce(ref("product.config.specification"), ref("helpers.dcsDefaults.specification")),
          quantity: coalesce(ref("product.config.quantity"), ref("helpers.dcsDefaults.quantity")),
          elasticBandwidth: ifElse(eq(ref("product.config.elasticBandwidth"), "Buy later"), "Buy later", "Buy now"),
          bandwidthMbit: coalesce(ref("product.config.bandwidthMbit"), ref("helpers.dcsDefaults.bandwidthMbit")),
          usageHours: coalesce(ref("product.config.usageHours"), ref("helpers.dcsDefaults.usageHours")),
        },
        nextRegion: coalesce(ref("product.config.region"), ref("regionValue")),
      },
      {
        handled: false,
        error: "This product cannot be edited from the calculator.",
      },
    ),
  },
} as const satisfies ConfigurableServiceBundleDefinition;

export const serviceDefinition = configurableServiceBundle.service;
export const pricingDefinition = configurableServiceBundle.pricing;
